### ISSUE TITLE
Dados sem retorno

### ISSUE THREAD

**Issue by Guilherme-Joviniano** [Augustocoder/SherlockBase#1]
Testei o serviço e está sem retorno algum de dados

**Comment by Augustocoder** [comment]
Irei verificar amanhã de manhã, obrigado.

Em sex., 20 de jan. de 2023 às 21:37, Guilherme Joviniano de Sousa <
***@***.***> escreveu:

**Comment by Augustocoder** [comment]
**Opa está funcionando sim Guilherme. Verifica se você instalou corretamente o XAMPP em seu Computador.**
![image](https://user-images.githubusercontent.com/121616883/213914114-49bc5b67-5eb1-4828-b529-95b661aa0d6d.png)

**Comment by Guilherme-Joviniano** [comment]
Acredito que nao, poderia disponibilizar as versoes utilizadas?

**Comment by Augustocoder** [comment]
> Acredito que nao, poderia disponibilizar as versoes utilizadas?

Faça um seguinte, reinstale o Xampp e coloque os arquivos no Htdocs. Verifique se o CURL do PHP está funcionando.
